release:
  github:
    owner: Matt-Gleich
    name: "ctree"
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - tap:
      owner: Matt-Gleich
      name: tap
    folder: Formula
    homepage: "https://github.com/Matt-Gleich/ctree"
    description: "🎄 A Christmas tree right from your terminal!"
    commit_author:
      name: Matt-Gleich
      email: email@mattglei.ch
