release:
  github:
    owner: gleich
    name: "ctree"
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - tap:
      owner: gleich
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/gleich/ctree"
    description: "🎄 A Christmas tree right from your terminal!"
    commit_author:
      name: gleich
      email: email@mattglei.ch
